site_name: The Termina Book

nav:
  - Home: index.md
  - Foreword: foreword.md
  - Getting started:
    - Installation: started/install.md
    - Hello, Real-Time World!: started/hello-world.md
  - Building our first application: tutorial.md
copyright: Copyright &copy; 2022 - 2025 The Termina Project Contributors

theme: 
  name: material
  logo: assets/logo_termina.png
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
